# ZMK still uses Zephyr's deprecated KSCAN subsystem for keyboard scanning.
CONFIG_WARN_DEPRECATED=n

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n

CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_CLICKTAPTOE_AS5600_SCROLL=y
CONFIG_CLICKTAPTOE_STATUS_LED=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=300
